simplemooc/accounts/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView, LogoutView
from simplemooc.accounts import views
from django.conf import settings
from simplemooc import urls

urlpatterns = [
    #re_path(r'^(?P<pk>\d+)$', views.details, name='details'),
    re_path(r'^entrar/$', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    re_path(r'^sair/$', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    re_path(r'^cadastre-se/$', views.register, name='register'),
    re_path(r'^editar/$', views.edit, name='edit'),
    re_path(r'^editar-senha/$', views.edit_password, name='edit_password'),
    re_path(r'^nova-senha/$', views.password_reset, name='password_reset'),
    re_path(r'^confirmar-nova-senha/(?P<key>\w+)/$', views.password_reset_confirm, name='password_reset_confirm'),
    re_path(r'^$', views.dashboard, name='dashboard'),
]

simplemooc/courses/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from simplemooc.courses import views
from simplemooc import urls

urlpatterns = [
    #re_path(r'^(?P<pk>\d+)$', views.details, name='details'),
    re_path(r'(?P<slug>[\w_-]+)$', views.details, name='details'),
    re_path(r'(?P<slug>[\w_-]+)/inscricao/$', views.enrollment, name='enrollment'),
    re_path(r'(?P<slug>[\w_-]+)/anuncios/$', views.announcements, name='announcements'),
    re_path(r'(?P<slug>[\w_-]+)/anuncios/(?P<pk>\d+)/$', views.show_announcement, name='show_announcement'),
    re_path(r'(?P<slug>[\w_-]+)/cancelar-inscricao/$', views.undo_enrollment, name='undo_enrollment'),
    re_path(r'(?P<slug>[\w_-]+)/aulas/$', views.lessons, name='lessons'),
    re_path(r'(?P<slug>[\w_-]+)/aulas/(?P<pk>\d+)/$', views.lesson, name='lesson'),
    re_path(r'(?P<slug>[\w_-]+)/materiais/(?P<pk>\d+)/$', views.material, name='material'),
    re_path(r'^$', views.index, name='index'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    re_path(r'^conta/', include(('simplemooc.accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'^cursos/', include(('simplemooc.courses.urls', 'courses'), namespace='courses')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include(('simplemooc.core.urls', 'core'), namespace='core')),
]

# Se for ambiente de desevolvimento
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplemooc/accounts/models.py
from django.db import models
from django.core import validators
from django.contrib.auth.models import (AbstractBaseUser, PermissionsMixin, UserManager)
from django.conf import settings
from simplemooc.core import utils
import re

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        'Nome de Usuário', max_length=30, unique=True, 
        validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
            'O nome de usuário só pode conter letras, digitos ou os '
            'seguintes caracteres: @/./+/-/_', 'invalid')]
    )
    email = models.EmailField('E-mail', unique=True)
    name = models.CharField('Nome', max_length=100, blank=True)
    is_active = models.BooleanField('Está ativo?', blank=True, default=True)
    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)
    date_joined = models.DateTimeField('Data de entrada', auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class PasswordReset(models.Model):
    
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Usuário', on_delete=models.CASCADE, related_name='resets')
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    confirmed = models.BooleanField('Confirmado?', blank=True, default=False)

    def __str__(self):
        return '{0} - {1}'.format(self.user, self.created_at)

    class Meta:
        verbose_name = 'Nova senha'
        verbose_name_plural = 'Novas senhas'
        ordering = ['-created_at']

simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from simplemooc.core.utils import generate_hash_key
from simplemooc.core.mail import send_mail_template
from .models import PasswordReset

User = get_user_model()

class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirmação de Senha', widget=forms.PasswordInput)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2
    
    # Método para salvar os dados do usuário (primeiro apenas valida[commit=False] e depois salva definitivamente)
    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email']        

class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name']

class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            return email
        raise forms.ValidationError('Nenhum usuário encontrado com este e-mail!')

    def save(self):
        user = User.objects.get(email=self.cleaned_data['email'])
        key = generate_hash_key(user.username)
        reset = PasswordReset(key=key, user=user)
        reset.save()
        template_name = 'accounts/password_reset_mail.html'
        subject = 'Redefinir senha'
        context = {
            'reset': reset,
        }
        send_mail_template(subject, template_name, context, [user.email])

simplemooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import (UserCreationForm, PasswordChangeForm, SetPasswordForm)
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages

from simplemooc.courses.models import Enrollment
from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset

User = get_user_model()

def register(request):
    template_name = 'accounts/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                request,
                username=user.username, password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('core:home')
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)

def logout(request):
    return redirect('core:home')

def password_reset(request):
    template_name = 'accounts/password_reset.html'
    context = {}
    form = PasswordResetForm(request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

def password_reset_confirm(request, key):
    template_name = 'accounts/password_reset_confirm.html'
    context = {}
    reset = get_object_or_404(PasswordReset, key=key)
    form = SetPasswordForm(user=reset.user, data=request.POST or None)
    if form.is_valid():
        form.save()
        context['success'] = True
    context['form'] = form
    return render(request, template_name, context)

@login_required
def dashboard(request):
    template_name = 'accounts/dashboard.html'
    context = {}
    return render(request, template_name, context)

@login_required
def edit(request):
    template_name = 'accounts/edit.html'
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Dados alterados com sucesso!')
            return redirect('accounts:dashboard')
    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request, template_name, context)

@login_required
def edit_password(request):
    template_name = 'accounts/edit_password.html'
    context = {}
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            form = PasswordChangeForm(user=request.user)
            context['success'] = True
    else:
        form = PasswordChangeForm(user=request.user)
    context['form'] = form
    return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}

{% load courses_tags %}

{% block content %}
{% load_my_courses user as enrollments %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <ul class="breadcrumb">
                {% block breadcrumb %}
                <li><a href="{% url 'accounts:dashboard' %}">Meu painel</a></li>
                {% endblock %}
            </ul>
        </div>
        <div class="pure-u-1-3">
            <div class="pure-menu pure-menu-open">
                <ul>
                    <li class="pure-menu-heading">
                        Bem vindo, {{ user }}
                    </li>
                    {% block menu_options %}
                    <li class="pure-menu-heading">Meus Cursos</li>
                    {% for enrollment in enrollments %}
                    <li>
                        <a href="{% url 'courses:announcements' enrollment.course.slug %}">
                            <i class="fa fa-book"></i>
                            {{ enrollment.course }}
                        </a>
                    </li>
                    {% empty %}
                    <li>Nenhum curso encontrado</li>
                    {% endfor %}
                    <li class="pure-menu-heading">Minha conta</li>
                    <li>
                        <a href="{% url 'accounts:edit' %}">
                            <i class="fa fa-cog"></i>
                            Editar conta
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:edit_password' %}">
                            <i class="fa fa-lock"></i>
                            Editar senha
                        </a>
                    </li>
                    {% endblock %}
                </ul>
            </div>
        </div>
        <div class="pure-u-2-3">
            <div class="inner">
                {% block dashboard_content %}
                <li class="pure-menu-heading">Meus Cursos</li>
                {% for enrollment in enrollments %}
                <div class="well">
                    <h3>
                        {{ enrollment.course }} ({{enrollment.course.start_date|date:'d/m/Y'|default:'Sem data de início'}})
                    </h3>
                    {{ enrollment.course.description|linebreaks }}
                    <div class="pure-controls">
                        <a href="{% url 'courses:announcements' enrollment.course.slug %}" class="pure-button pure-button-primary">Acessar</a>
                        <a href="{% url 'courses:undo_enrollment' enrollment.course.slug %}" class="pure-button button-error">Cancelar</a>
                    </div>
                </div>
                {% empty %}
                <li>Nenhum curso encontrado</li>
                {% endfor %}
            {% endblock %}
            </div>
        </div>

    </div>

{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends 'accounts/dashboard.html' %}

    {% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit' %}">Editar conta</a></li>

{% endblock %}
{% block dashboard_content %}

    <form class="pure-form pure-form-stacked" method="POST">
        {% csrf_token %}
        <fieldset>
            {{ form.non_fiels_errors }}
            {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Salvar</button>
            </div>
        </fieldset>
    </form>

{% endblock %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends 'accounts/dashboard.html' %}

    {% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_password' %}">Editar conta</a></li>

{% endblock %}
{% block dashboard_content %}

    <form class="pure-form pure-form-stacked" method="POST">
        {% csrf_token %}
        {% if success %}
        <p>A senha foi alterada com sucesso</p>
        {% endif %}
        <fieldset>
            {{ form.non_fiels_errors }}
            {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}
            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Alterar</button>
            </div>
        </fieldset>
    </form>

{% endblock %}

simplemooc/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe os dados do cadastro</h2>
            <form class="pure-form pure-form-aligned" method="POST">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_fiels_errors }}
                    {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                    </div>
                </fieldset>
                <p>
                    Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br>
                    Esqueceu a senha? <a href="{% url 'accounts:password_reset' %}" title="">Nova senha</a> <br>
                </p>
            </form>

        </div>

    </div>

{% endblock %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            {% if success %}
            <p>O e-mail foi enviado para você com mais detalhes de como alterar sua senha</p>
            {% else %}
            <h2>Informe seu e-mail</h2>
            <form class="pure-form pure-form-aligned" method="POST">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_fiels_errors }}
                    {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
                    </div>
                </fieldset>
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            {% if success %}
            <p>Sua senha foi alterada com sucesso</p>
            {% else %}
            <h2>Informe sua nova senha</h2>
            <form class="pure-form pure-form-aligned" method="POST">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_fiels_errors }}
                    {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                    </div>
                </fieldset>
            </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_mail.html
<p>Para redefinir sua senha acesse o link: <br>
<a href="http://127.0.0.1:8000{% url 'accounts:password_reset_confirm' reset.key %}">Criar nova senha</a>
</p>

simplemooc/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe os dados</h2>
            <form class="pure-form pure-form-aligned" method="POST">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_fiels_errors }}
                    {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}